### ISSUE TITLE
Routing Resource Resolvers

### ISSUE THREAD

**Issue by beberlei** [KnpLabs/geekweek12#14]
Would it be possible to define the resource resolvers at a more global level in the controller? I suppose its the same anyways:
- We need a form
- We need a new object
- We need to load an object by some identifier

Most of the actions are variants of the tree.

The current configuration necessary requires more lines of code than doing the same in PHP code.

**Comment by everzet** [comment]
More global level?

**Comment by beberlei** [comment]
https://gist.github.com/2afb133c07ab60fae6e1

**Comment by everzet** [comment]
You already can specify `defaults` on all 3 levels (`all`, `resources`, `collections`):

``` yml
App:Cheeses:
    defaults:
        _resources:
            cheese: { service: orm.cheese_repository } # defaults to find($id)
            newCheese: { service: orm.cheese_repository, method: createNew }

            form: { form: chesse, purpose: new }
            editForm: { form: chesse, purpose: edit }

    collections:
        defaults:
            _resoruces: [] # collection-specific resolvers

    resources:
        defaults:
            _resoruces: [] # resource-specific resolvers
```

On global, `resources` & `collections`. They are merged downward.
And yeah. We've talked about defaulting to `find($id)` at the very beginning of resolvers but then suddenly forgot bout it. Also, short notation for forms creation looks nice too.

/cc @Herzult
