### ISSUE TITLE
Imposible to use bootstrap assets without config

### ISSUE THREAD

**Issue by PedroTroller** [KnpLabs/geekweek12#5]
To use Twitter Bootstrap integrated in KnpRadBundle, you need to add RadBundle on assetic configurtation

``` yml
# Assetic Configuration
assetic:
    bundles:        [ ... , KnpRadBundle ]
```
